apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: celery-worker # Must match the locally built image name
          imagePullPolicy: Never # Prevent Kubernetes from trying to pull from DockerHub
          env:
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
          resources:
            requests:
              cpu: "100m" # Request 100 milliCPUs (0.1 vCPU)
              memory: "256Mi" # Request 256MB of RAM
            limits:
              cpu: "500m" # Limit to 500 milliCPUs (0.5 vCPU)
              memory: "512Mi" # Limit to 512MB of RAM

